### ISSUE TITLE
Add missing robots from the ros wiki page

### ISSUE THREAD

**Issue by sloretz** [ros-infrastructure/robots.ros.org#26]
On WIki, but not on robots.ros.org

- [x] 0x Alpha by Nex Robotics (#31)
- ~~420 Omni Stanley Innovation V3 Segway~~ RMPv3
- [x] AR10 Robotic Hand (#37)
- [x] ASIMoV Robotics X-Terrabot (#38)
- [x] AUBO Robotics (#39)
- [x] BIG-i (#42)
- [x] Clearpath Robotics Ridgeback (#43)
- [x] Clearpath Robotics Warthog (#44)
- [x] Commonplace Robotics Manipulation Platform (#46)
- [x] Commonplace Robotics Mover (#47)
- [x] Commonplace Robotics SRA Service Robot Arm (#48)
- [x] CoroWare Corobot (#49)
- ~~Denso VS060~~ No wiki page
- ~~Eddiebot~~ Wiki page for package doesn't describe robot
- ~~Fanuc Robotics (ROS-Industrial)~~ Not sure where on wiki to pull description from
- ~~GeRo (open source humanoid robot)~~ Empty wiki page
- ~~GoThere! Robot~~ Empty wiki page
- [x] Han's Robotics (#50)
- ~~i-Cart mini~~ Empty wiki page
- [x] Ingeniarius ForteRC (#51)
- [x] Intel Edison (#56)
- [x] iRobot Roomba (#57)
- [x] Kawada Nextage / Hiro (#59)
- [x] Kinova JACO (#60)
- [x] Kinova MICO (#61)
- ~~Kobuki~~ Not sure where on wiki to pull description from
- [x] Lego NXT (#62)
- [x] Maggie (#63)
- [x] Mecanumbot (#64)
- [x] Merlin miabotPro (#65)
- ~~Milvus Robotics ATR~~ Empty wiki page
- [x] Milvus Robotics MRP2 (#66)
- ~~Milvus Robotics Robin~~ Empty wiki page
- ~~Motoman,  Yaskawa (ROS-Industrial)~~ Not sure where on wiki page to pull description from
- [x] Nav2 (#67)
- ~~Neobotix mp-500~~ Bot specific page doesn't have enough sentences to make a description
- ~~Neobotix mpo-500~~ Bot specific page doesn't have enough sentences to make a description
- ~~Neobotix mpo-700~~ Bot specific page doesn't have enough sentences to make a description
- ~~Open Unit Robot~~ No image
- [x] Otto Bock SensorHand Speed (#68)
- [x] PAL Robotics PMB-2
- ~~RazBot~~ No wiki page
- ~~Robonaut 2~~ Empty wiki page
- [x] RoboTiCan ARMadillo (#69)
- ~~RoboTiCan Komodo~~ No bot specific wiki page
- ~~RoboTiCan Lizi~~ No bot specific wiki page
- [x] ROBOTIS Manipulator-H (#70)
- [x] Robotnik CROM (#71)
- [x] Roch
- ~~ROS-Industrial~~ Not hardware
- ~~Ros2Bot~~ Empty wiki page
- [x] Shadow Hand (https://github.com/ros-infrastructure/robots.ros.org/pull/53)
- [x] Softbank Pepper (#72)
- [x] Spark (#74)
- [x] TUlip (#75)
- ~~Universal Robots (ROS-Industrial)~~ Not sure where on wiki page to pull description from
- ~~Videre Erratic~~ Not sure where on wiki page to pull description from
- [x] WheeledRobin
- [x] xiaoqiang (#76)

**Comment by tfoote** [comment]
@sloret I see a bunch that are on robots.ros.org on that list I added links next to them.

Note that we also have the new policy not to have multiple entries for variants of a robot: http://robots.ros.org/contributing/ so some of these should collapse.

And I'd also like to consider a review of if the robots listed to require that they actually have a landing page

**Comment by sloretz** [comment]
Whoops I missed a lot.

Where did the long description in the current posts come from? I tried clicking a random sample of links on the backup of the wiki, but every one I clicked appears to be broken. ex: http://wiki.ros.org/Robots/Robots/Erle-brain

**Comment by tfoote** [comment]
With the backup copy in a subdirectory relative links are broken. You should remove the duplicate `Robots/` from the path if you get the duplicates like that. ala http://wiki.ros.org/Robots/Erle-brain

**Comment by sloretz** [comment]
I updated the list in this ticket to not include robots that don't have a wiki page or the page has fewer than 3 sentences describing the robot.

**Comment by tfoote** [comment]
:tada: @sloretz Thanks for working through all these!!

**Comment by mikaelarguedas** [comment]
Wow ! thanks @sloretz !!
